# Site settings
author: Teresa Mendoza
title: 
header-img: img/home-bg.png
email: tmendoza657@gmail.com
copyright_name: Teresa Mendoza
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tmm657

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
